### PR TITLE
ENH: adds ECLIPSE profile, updates README

### PR DESCRIPTION
**Pull request by ChrisKeefe**

### CODE REVIEW

**Review by David-Rod — DISMISSED** [review]
Made changes to eclipse format. Seems to be working (LGTM).

**Comment by ChrisKeefe** [comment]
@David-Rod, minor change to README formatting to emphasize that these profiles are at-your-own-risk. Mind re-reviewing? 

Thx,
CK

**Review by David-Rod — APPROVED** [review]
LGTM

**Comment by ChrisKeefe** [comment]
Thanks bud!


*Chris Keefe360.389.1092*

Student Research Software Engineer
Caporaso Lab
Northern Arizona University

**Pull request merged**
